server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/vue_blog?useUnicode=true&characterEncoding=utf-8&userSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qymlxin.pojo
  configuration:
    map-underscore-to-camel-case: true

